### ISSUE TITLE
не загружаются статические ассеты

### ISSUE THREAD

**Issue by JohnFrolov** [codyfet/tracked#69]
![image](https://user-images.githubusercontent.com/4136877/146001213-29d344ba-ffe8-440c-aab3-3336acf5a053.png)
![image](https://user-images.githubusercontent.com/4136877/146001358-f37b9f49-6501-47d5-ba51-42736930d2cf.png)

**Comment by codyfet** [comment]
Связано с https://github.com/codyfet/tracked/issues/55

Вообще хочется сделать так, чтобы юзеры могли свой аватар загружать

**Comment by codyfet** [comment]
Исправлено в https://github.com/codyfet/tracked/pull/80

Добавлена возможность сохранять свой аватар.
